import CatalogueImg from "./CatalogueImg";

const CatalogueData = [
	{
		id: "HTML",
		image: CatalogueImg.html,
		video:
			"https://res.cloudinary.com/codewithmosh/video/upload/v1684540144/promo-videos/htmlcss.mp4",
		course: "HTML & CSS",
		description:
			"En este curso aprenderás a crear y estilizar páginas web. Mejora tus habilidades con proyectos interactivos y ejemplos reales.",
		calification: "4.9 ⭐⭐⭐⭐",
		detail1: "Detalle 1 ",
		detail2: "Detalle 2",
		detail3: "Detalle 3",
		detail4: "Detalle 4",
		detail5: "Detalle 5",
		detail6: "Detalle 6",
		detail7: "Detalle 7",
		detail8: "Detalle 8",
		learn1: "Que aprenderas 1",
		learn2: "Que aprenderas 2",
		learn3: "Que aprenderas 3",
		learn4: "Que aprenderas 4",
		learn5: "Que aprenderas 5",
		learn6: "Que aprenderas 6",
		learn7: "Que aprenderas 7",
		content1: " Contenido 1",
		content2: " contenido 2",
		content3: " Contenido 3",
		content4: " Contenido 4",
		content5: " Contenido 5",
		content6: " Contenido 6",
		content7: " Contenido 7",
		content8: " Contenido 8"
	},

	{
		id: "JAVASCRIPT",
		image: CatalogueImg.js,
		video:
			"https://player.hotmart.com/embed/4RbQ35aQZv?signature=cw2H9a8E9WVUaBMlNtKqyLonP6tw4KherUD1doYESN-YNTts-eKkKevRUi8HShlXpaOKG0iZ4I_YOw4d762UKmF68y7ySYnkzZyjNH8MbK7JK8LnizGqqzoZMoeKCxyesHRSnNx4l-Nqv-r8Uzi5LYTNfKYdkwKoIDbY_883KqA4G2eRctTgoqncQ4K6iN14kGkp-DPle8b53Rg-_QzwKnYjNI7x0sfKQXEv63CeTVekMV8Sy767hpl51Lt6EE0d4xc2C0hp9F0l1-obVTI1IIE812VGrhhiUYJn7cdvNWl7mxycgOeplumk_OOFSJFl3gP6f4Gs4aCHSWvm9dp9Ug%3D%3D&token=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c&autoplay=autoplay",
		course: "JAVASCRIPT",
		description:
			"Aprende JavaScript desde cero y domina las bases de la programación web. ",
		calification: "4.9 ⭐⭐⭐⭐",
		detail1: "Detalle 1 ",
		detail2: "Detalle 2",
		detail3: "Detalle 3",
		detail4: "Detalle 4",
		detail5: "Detalle 5",
		detail6: "Detalle 6",
		detail7: "Detalle 7",
		detail8: "Detalle 8",
		learn1: "Que aprenderas 1",
		learn2: "Que aprenderas 2",
		learn3: "Que aprenderas 3",
		learn4: "Que aprenderas 4",
		learn5: "Que aprenderas 5",
		learn6: "Que aprenderas 6",
		learn7: "Que aprenderas 7",
		content1: " Contenido 1",
		content2: " contenido 2",
		content3: " Contenido 3",
		content4: " Contenido 4",
		content5: " Contenido 5",
		content6: " Contenido 6",
		content7: " Contenido 7",
		content8: " Contenido 8"
	},
	{
		id: "NEXT",
		image: CatalogueImg.next,
		video:
			"https://res.cloudinary.com/codewithmosh/video/upload/v1694364873/promo-videos/nextjs-part1.mp4",
		course: "NEXT",
		description:
			"Aprende a crear aplicaciones web rápidas y eficientes con Next.js, aprovechando su potente renderizado y optimización.",
		calification: "4.9 ⭐⭐⭐⭐",
		detail1: "Detalle 1 ",
		detail2: "Detalle 2",
		detail3: "Detalle 3",
		detail4: "Detalle 4",
		detail5: "Detalle 5",
		detail6: "Detalle 6",
		detail7: "Detalle 7",
		detail8: "Detalle 8",
		learn1: "Que aprenderas 1",
		learn2: "Que aprenderas 2",
		learn3: "Que aprenderas 3",
		learn4: "Que aprenderas 4",
		learn5: "Que aprenderas 5",
		learn6: "Que aprenderas 6",
		learn7: "Que aprenderas 7",
		content1: " Contenido 1",
		content2: " contenido 2",
		content3: " Contenido 3",
		content4: " Contenido 4",
		content5: " Contenido 5",
		content6: " Contenido 6",
		content7: " Contenido 7",
		content8: " Contenido 8"
	},

	{
		id: "SQL",
		image: CatalogueImg.sql,
		video:
			"https://player.hotmart.com/embed/Yq2om9PdLa?signature=0E3kL60RPq_WFD2ZLdVaKhzdEkxtSAaRJJ1JfHVoO7c8o3tIvGUu1p0B_x_Mu9MsZtn3H43bcelaQ1y7O9GIRvV1wBhsUO0ADvVbTbkfDzBGHiiLXtYVtMJtTjqNdD-dvAJCN6DDELTe5KzLYfVO47vh4kj04Hdfv4XKDul4jP5Sqvwx_kL3sdu4XCw0FnLQPqe9qIUGOyhcTKV_ypPAKcV7Cnq7lGoZvxUeX9QMdqZn-9CGSGqeuwQbzXzwROE9FalSeAzDwXo52YSww1u17QAb8hTKBKAPOtBX-RHwTpuLzuENvm69SlOR__KvCOsUC6daWIFFzqoh5g9Tm4KheA%3D%3D&token=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c&autoplay=autoplay",
		course: "SQL",
		description:
			"Domina SQL para gestionar y analizar datos de manera efectiva en cualquier base de datos.",
		calification: "4.9 ⭐⭐⭐⭐",
		detail1: "Detalle 1 ",
		detail2: "Detalle 2",
		detail3: "Detalle 3",
		detail4: "Detalle 4",
		detail5: "Detalle 5",
		detail6: "Detalle 6",
		detail7: "Detalle 7",
		detail8: "Detalle 8",
		learn1: "Que aprenderas 1",
		learn2: "Que aprenderas 2",
		learn3: "Que aprenderas 3",
		learn4: "Que aprenderas 4",
		learn5: "Que aprenderas 5",
		learn6: "Que aprenderas 6",
		learn7: "Que aprenderas 7",
		content1: " Contenido 1",
		content2: " contenido 2",
		content3: " Contenido 3",
		content4: " Contenido 4",
		content5: " Contenido 5",
		content6: " Contenido 6",
		content7: " Contenido 7",
		content8: " Contenido 8"
	},
	{
		id: "C++",
		image: CatalogueImg.cSharp,
		video:
			"https://res.cloudinary.com/codewithmosh/video/upload/v1684540279/promo-videos/cplusplus.mp4",
		course: "C++",
		description:
			"Descubre los fundamentos de C++ y desarrolla habilidades para crear aplicaciones eficientes y de alto rendimiento.",
		calification: "4.9 ⭐⭐⭐⭐",
		detail1: "Detalle 1 ",
		detail2: "Detalle 2",
		detail3: "Detalle 3",
		detail4: "Detalle 4",
		detail5: "Detalle 5",
		detail6: "Detalle 6",
		detail7: "Detalle 7",
		detail8: "Detalle 8",
		learn1: "Que aprenderas 1",
		learn2: "Que aprenderas 2",
		learn3: "Que aprenderas 3",
		learn4: "Que aprenderas 4",
		learn5: "Que aprenderas 5",
		learn6: "Que aprenderas 6",
		learn7: "Que aprenderas 7",
		content1: " Contenido 1",
		content2: " contenido 2",
		content3: " Contenido 3",
		content4: " Contenido 4",
		content5: " Contenido 5",
		content6: " Contenido 6",
		content7: " Contenido 7",
		content8: " Contenido 8"
	},

	{
		id: "DJANGO",
		image: CatalogueImg.django,
		video:
			"https://res.cloudinary.com/codewithmosh/video/upload/v1684768296/promo-videos/dj.mp4",
		course: "DJANGO",
		description:
			"Aprende a construir aplicaciones web robustas y escalables con Django, el potente framework de Python.",
		calification: "4.9 ⭐⭐⭐⭐",
		detail1: "Detalle 1 ",
		detail2: "Detalle 2",
		detail3: "Detalle 3",
		detail4: "Detalle 4",
		detail5: "Detalle 5",
		detail6: "Detalle 6",
		detail7: "Detalle 7",
		detail8: "Detalle 8",
		learn1: "Que aprenderas 1",
		learn2: "Que aprenderas 2",
		learn3: "Que aprenderas 3",
		learn4: "Que aprenderas 4",
		learn5: "Que aprenderas 5",
		learn6: "Que aprenderas 6",
		learn7: "Que aprenderas 7",
		content1: " Contenido 1",
		content2: " contenido 2",
		content3: " Contenido 3",
		content4: " Contenido 4",
		content5: " Contenido 5",
		content6: " Contenido 6",
		content7: " Contenido 7",
		content8: " Contenido 8"
	},
	{
		id: "DOCKER",
		image: CatalogueImg.docker,
		video:
			"https://res.cloudinary.com/codewithmosh/video/upload/v1684768693/promo-videos/dockerc.mp4",
		course: "DOCKER",
		description:
			"Domina Docker para crear, desplegar y gestionar aplicaciones en contenedores de manera eficiente y escalable.",
		calification: "4.9 ⭐⭐⭐⭐",
		detail1: "Detalle 1 ",
		detail2: "Detalle 2",
		detail3: "Detalle 3",
		detail4: "Detalle 4",
		detail5: "Detalle 5",
		detail6: "Detalle 6",
		detail7: "Detalle 7",
		detail8: "Detalle 8",
		learn1: "Que aprenderas 1",
		learn2: "Que aprenderas 2",
		learn3: "Que aprenderas 3",
		learn4: "Que aprenderas 4",
		learn5: "Que aprenderas 5",
		learn6: "Que aprenderas 6",
		learn7: "Que aprenderas 7",
		content1: " Contenido 1",
		content2: " contenido 2",
		content3: " Contenido 3",
		content4: " Contenido 4",
		content5: " Contenido 5",
		content6: " Contenido 6",
		content7: " Contenido 7",
		content8: " Contenido 8"
	},

	{
		id: "REACT TYPESCRIPT",
		image: CatalogueImg.reactTP,
		video:
			"https://res.cloudinary.com/codewithmosh/video/upload/v1684768181/promo-videos/tscript.mp4",
		course: "REACT CON TYPESCRIPT",
		title: "Aprende React con TypeScript: Desarrollo Moderno",
		description:
			"Descubre cómo construir interfaces interactivas y escalables usando React y TypeScript para aplicaciones web robustas.",
		calification: "4.9 ⭐⭐⭐⭐",
		detail1: "Detalle 1 ",
		detail2: "Detalle 2",
		detail3: "Detalle 3",
		detail4: "Detalle 4",
		detail5: "Detalle 5",
		detail6: "Detalle 6",
		detail7: "Detalle 7",
		detail8: "Detalle 8",
		learn1: "Que aprenderas 1",
		learn2: "Que aprenderas 2",
		learn3: "Que aprenderas 3",
		learn4: "Que aprenderas 4",
		learn5: "Que aprenderas 5",
		learn6: "Que aprenderas 6",
		learn7: "Que aprenderas 7",
		content1: " Contenido 1",
		content2: " contenido 2",
		content3: " Contenido 3",
		content4: " Contenido 4",
		content5: " Contenido 5",
		content6: " Contenido 6",
		content7: " Contenido 7",
		content8: " Contenido 8"
	},
	{
		id: "TYPESCRIPT",
		image: CatalogueImg.typescript,
		video:
			"https://res.cloudinary.com/codewithmosh/video/upload/v1684768181/promo-videos/tscript.mp4",
		course: "TYPESCRIPT",
		description:
			"Aprende TypeScript para mejorar tus habilidades en JavaScript, creando aplicaciones más seguras y mantenibles.",
		calification: "4.9 ⭐⭐⭐⭐",
		detail1: "Detalle 1 ",
		detail2: "Detalle 2",
		detail3: "Detalle 3",
		detail4: "Detalle 4",
		detail5: "Detalle 5",
		detail6: "Detalle 6",
		detail7: "Detalle 7",
		detail8: "Detalle 8",
		learn1: "Que aprenderas 1",
		learn2: "Que aprenderas 2",
		learn3: "Que aprenderas 3",
		learn4: "Que aprenderas 4",
		learn5: "Que aprenderas 5",
		learn6: "Que aprenderas 6",
		learn7: "Que aprenderas 7",
		content1: " Contenido 1",
		content2: " contenido 2",
		content3: " Contenido 3",
		content4: " Contenido 4",
		content5: " Contenido 5",
		content6: " Contenido 6",
		content7: " Contenido 7",
		content8: " Contenido 8"
	}
];

export default CatalogueData;
