# Generated by Django 5.1 on 2024-09-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_cover_image_remove_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
