# Generated by Django 5.1 on 2024-09-16 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_module_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='enrollments', to='api.course'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='api_categor_name_53a3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['code'], name='api_certifi_code_e37b51_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='api_course_slug_af2ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user'], name='api_enrollm_user_id_711045_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course'], name='api_enrollm_course__c7761e_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['title'], name='api_module_title_d3266e_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course'], name='api_module_course__cedea4_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role'], name='api_profile_role_c920da_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['enrollment'], name='api_progres_enrollm_362396_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['enrollment'], name='api_rating_enrollm_8905cb_idx'),
        ),
    ]
