# Generated by Django 5.1 on 2024-09-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_module_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
