name: Run main.py

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  ping_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests

      - name: Wait before sending ping
        run: sleep 10

      - name: Send ping to Render
        run: python .github/workflows/main.py